name: quality_check_flow
on:
  push:
    branches:
      - main
      - dev
      - dev-workflows
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  quality_check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Check out our code
        uses: actions/checkout@v5
      
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version-file: "app/.python-version"
      
      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.5.18"
          enable-cache: true
          cache-dependency-glob: "app/uv.lock"
      
      - name: 📦 Install Dependencies (Locked)
        run: uv sync --locked --all-extras --dev
      
      - name: Run Ruff Lint
        run: uv run ruff check --output-format=github src/
      
      - name: Run Ruff Format
        run: uv run ruff format --check --output-format=github src/
